import type { CoreColorToken, ThemeColor } from './tokens.ts';

function rgb(r: number, g: number, b: number): ThemeColor {
  return { kind: 'rgb', r, g, b };
}

export const modernColors = {
  'app.background': rgb(7, 12, 12),
  'app.foreground': rgb(218, 225, 220),
  'surface.background': rgb(10, 16, 16),
  'surface.foreground': rgb(218, 225, 220),
  'surface.border': rgb(58, 70, 70),
  'surface.title': rgb(91, 240, 83),
  'surface.bar.background': rgb(14, 21, 21),
  'surface.bar.border': rgb(74, 87, 87),
  'surface.raised.background': rgb(17, 25, 24),
  'surface.raised.border': rgb(81, 96, 94),
  'surface.inset.background': rgb(5, 9, 9),
  'surface.inset.border': rgb(45, 55, 55),
  'surface.selected.background': rgb(24, 92, 31),
  'surface.selected.border': rgb(75, 220, 72),
  'surface.warning.background': rgb(45, 33, 8),
  'surface.warning.border': rgb(218, 164, 30),
  'surface.danger.background': rgb(50, 18, 18),
  'surface.danger.border': rgb(245, 86, 70),
  'surface.success.background': rgb(18, 52, 22),
  'surface.success.border': rgb(72, 225, 69),
  'surface.shadow': rgb(2, 5, 5),
  'text.default': rgb(218, 225, 220),
  'text.muted': rgb(128, 142, 138),
  'text.strong': rgb(244, 250, 246),
  'text.disabled': rgb(82, 94, 92),
  'link.foreground': rgb(88, 200, 255),
  'accent.primary': rgb(80, 235, 74),
  'accent.secondary': rgb(30, 228, 177),
  'status.info': rgb(80, 198, 255),
  'status.success': rgb(82, 234, 72),
  'status.warning': rgb(238, 176, 43),
  'status.error': rgb(255, 88, 72),
  'status.pending': rgb(145, 156, 152),
  'status.running': rgb(38, 205, 255),
  'scale.low': rgb(86, 218, 82),
  'scale.medium': rgb(197, 224, 84),
  'scale.high': rgb(238, 176, 43),
  'scale.critical': rgb(255, 88, 72),
  'selection.background': rgb(28, 102, 35),
  'selection.foreground': rgb(238, 255, 235),
  'focus.border': rgb(87, 246, 78),
  'focus.background': rgb(15, 54, 21),
  'control.background': rgb(13, 20, 20),
  'control.foreground': rgb(224, 231, 226),
  'control.border': rgb(82, 97, 96),
  'control.primary.background': rgb(88, 229, 75),
  'control.primary.foreground': rgb(5, 20, 8),
  'control.primary.border': rgb(117, 255, 105),
  'control.secondary.background': rgb(28, 39, 39),
  'control.secondary.foreground': rgb(222, 230, 226),
  'control.secondary.border': rgb(93, 111, 109),
  'control.track': rgb(63, 77, 75),
  'control.track.filled': rgb(83, 232, 75),
  'control.handle': rgb(235, 245, 238),
  'control.toggle.on.background': rgb(60, 174, 58),
  'control.toggle.off.background': rgb(72, 91, 89),
  'input.cursor': rgb(95, 252, 82),
  'input.placeholder': rgb(105, 118, 115),
  'editor.gutter.foreground': rgb(104, 119, 116),
  'editor.gutter.background': rgb(8, 14, 14),
  'editor.gutter.active.foreground': rgb(56, 231, 189),
  'editor.activeLine.background': rgb(14, 28, 27),
  'command.prompt': rgb(77, 230, 74),
  'command.match': rgb(242, 190, 55),
  'menu.match': rgb(242, 190, 55),
  'menu.selected': rgb(82, 229, 72),
  'tab.active.foreground': rgb(242, 249, 244),
  'tab.inactive.foreground': rgb(144, 157, 153),
  'tab.indicator': rgb(82, 234, 72),
  'badge.background': rgb(60, 173, 58),
  'badge.foreground': rgb(5, 19, 7),
  'keyHint.background': rgb(18, 25, 25),
  'keyHint.foreground': rgb(224, 231, 226),
  'table.header': rgb(196, 206, 201),
  'table.metric': rgb(222, 230, 226),
  'table.metadata': rgb(128, 142, 138),
  'tree.branch': rgb(86, 101, 99),
  'log.info': rgb(80, 198, 255),
  'log.metadata': rgb(145, 158, 154),
  'log.warning': rgb(238, 176, 43),
  'log.error': rgb(255, 88, 72),
  'log.timestamp': rgb(122, 218, 203),
  'scrollbar.track': rgb(53, 65, 64),
  'scrollbar.thumb': rgb(151, 166, 162),
  'diff.add': rgb(75, 222, 70),
  'diff.remove': rgb(255, 93, 75),
  'diff.context': rgb(130, 143, 139),
  'chart.axis': rgb(91, 106, 103),
  'chart.label': rgb(190, 204, 199),
  'chart.value': rgb(222, 230, 226),
  'chart.muted': rgb(74, 88, 86),
  'chart.baseline': rgb(90, 112, 108),
  'chart.positive': rgb(79, 224, 72),
  'chart.negative': rgb(47, 182, 255),
  'chart.series.1': rgb(79, 224, 72),
  'chart.series.2': rgb(47, 182, 255),
  'chart.series.3': rgb(238, 176, 43)
} satisfies Readonly<Record<CoreColorToken, ThemeColor>>;

export const highContrastColors = {
  ...modernColors,
  'app.background': { kind: 'ansi', value: 0 },
  'app.foreground': { kind: 'ansi', value: 15 },
  'surface.border': { kind: 'ansi', value: 15 },
  'surface.bar.border': { kind: 'ansi', value: 15 },
  'surface.raised.border': { kind: 'ansi', value: 15 },
  'surface.inset.border': { kind: 'ansi', value: 7 },
  'surface.selected.background': { kind: 'ansi', value: 15 },
  'surface.selected.border': { kind: 'ansi', value: 15 },
  'surface.warning.border': { kind: 'ansi', value: 11 },
  'surface.danger.border': { kind: 'ansi', value: 9 },
  'surface.success.border': { kind: 'ansi', value: 10 },
  'surface.shadow': { kind: 'ansi', value: 7 },
  'text.muted': { kind: 'ansi', value: 7 },
  'link.foreground': { kind: 'ansi', value: 14 },
  'accent.primary': { kind: 'ansi', value: 11 },
  'accent.secondary': { kind: 'ansi', value: 14 },
  'status.info': { kind: 'ansi', value: 14 },
  'status.success': { kind: 'ansi', value: 10 },
  'status.error': { kind: 'ansi', value: 9 },
  'status.warning': { kind: 'ansi', value: 11 },
  'status.pending': { kind: 'ansi', value: 7 },
  'status.running': { kind: 'ansi', value: 14 },
  'scale.low': { kind: 'ansi', value: 10 },
  'scale.medium': { kind: 'ansi', value: 11 },
  'scale.high': { kind: 'ansi', value: 11 },
  'scale.critical': { kind: 'ansi', value: 9 },
  'selection.background': { kind: 'ansi', value: 15 },
  'selection.foreground': { kind: 'ansi', value: 0 },
  'focus.border': { kind: 'ansi', value: 15 },
  'control.background': { kind: 'ansi', value: 0 },
  'control.foreground': { kind: 'ansi', value: 15 },
  'control.border': { kind: 'ansi', value: 15 },
  'control.primary.background': { kind: 'ansi', value: 15 },
  'control.primary.foreground': { kind: 'ansi', value: 0 },
  'control.primary.border': { kind: 'ansi', value: 15 },
  'control.secondary.background': { kind: 'ansi', value: 0 },
  'control.secondary.foreground': { kind: 'ansi', value: 15 },
  'control.secondary.border': { kind: 'ansi', value: 7 },
  'control.track': { kind: 'ansi', value: 7 },
  'control.track.filled': { kind: 'ansi', value: 15 },
  'control.handle': { kind: 'ansi', value: 15 },
  'control.toggle.on.background': { kind: 'ansi', value: 15 },
  'control.toggle.off.background': { kind: 'ansi', value: 7 },
  'input.cursor': { kind: 'ansi', value: 15 },
  'editor.gutter.foreground': { kind: 'ansi', value: 7 },
  'editor.gutter.background': { kind: 'ansi', value: 0 },
  'editor.gutter.active.foreground': { kind: 'ansi', value: 14 },
  'editor.activeLine.background': { kind: 'ansi', value: 0 },
  'command.prompt': { kind: 'ansi', value: 15 },
  'command.match': { kind: 'ansi', value: 11 },
  'menu.match': { kind: 'ansi', value: 11 },
  'menu.selected': { kind: 'ansi', value: 15 },
  'tab.active.foreground': { kind: 'ansi', value: 15 },
  'tab.inactive.foreground': { kind: 'ansi', value: 7 },
  'tab.indicator': { kind: 'ansi', value: 15 },
  'badge.background': { kind: 'ansi', value: 15 },
  'badge.foreground': { kind: 'ansi', value: 0 },
  'keyHint.background': { kind: 'ansi', value: 0 },
  'keyHint.foreground': { kind: 'ansi', value: 15 },
  'table.header': { kind: 'ansi', value: 15 },
  'table.metric': { kind: 'ansi', value: 15 },
  'table.metadata': { kind: 'ansi', value: 7 },
  'tree.branch': { kind: 'ansi', value: 7 },
  'log.info': { kind: 'ansi', value: 14 },
  'log.metadata': { kind: 'ansi', value: 7 },
  'log.warning': { kind: 'ansi', value: 11 },
  'log.error': { kind: 'ansi', value: 9 },
  'log.timestamp': { kind: 'ansi', value: 14 },
  'scrollbar.track': { kind: 'ansi', value: 7 },
  'scrollbar.thumb': { kind: 'ansi', value: 15 },
  'diff.add': { kind: 'ansi', value: 10 },
  'diff.remove': { kind: 'ansi', value: 9 },
  'diff.context': { kind: 'ansi', value: 7 },
  'chart.axis': { kind: 'ansi', value: 7 },
  'chart.label': { kind: 'ansi', value: 15 },
  'chart.value': { kind: 'ansi', value: 15 },
  'chart.muted': { kind: 'ansi', value: 7 },
  'chart.baseline': { kind: 'ansi', value: 7 },
  'chart.positive': { kind: 'ansi', value: 10 },
  'chart.negative': { kind: 'ansi', value: 14 },
  'chart.series.1': { kind: 'ansi', value: 10 },
  'chart.series.2': { kind: 'ansi', value: 14 },
  'chart.series.3': { kind: 'ansi', value: 13 }
} satisfies Readonly<Record<CoreColorToken, ThemeColor>>;
