export { terminalUiPackage } from './package.ts';
export type { RuntimeTarget, TerminalUiEntrypoint, TerminalUiPackage } from './package.ts';
export type { Result } from './result.ts';
export { ok, err } from './result.ts';
export type {
  TerminalDiagnostic,
  TerminalDiagnosticCode,
  TerminalDiagnosticValue,
  TerminalSeverity
} from './diagnostics.ts';
export { diagnostic, terminalDiagnosticCodes } from './diagnostics.ts';
export { TerminalUiError } from './errors.ts';

export {
  createBunTerminalHost,
  createDenoTerminalHost,
  createMemoryTerminalHost,
  createNodeTerminalHost,
  createPtyTerminalHost,
  createTerminalHost,
  detectTerminalCapabilities,
  restoreTerminalState
} from './host/index.ts';
export type {
  BunTerminalHostOptions,
  CreateTerminalHostOptions,
  DenoTerminalHostOptions,
  MemoryTerminalHost,
  MemoryTerminalHostOptions,
  NodeProcessLike,
  NodeReadableTerminalStream,
  NodeTerminalHostOptions,
  NodeTerminalSignal,
  NodeWritableTerminalStream,
  PtyTerminalHost,
  PtyTerminalHostOptions,
  RuntimeInputSource,
  RuntimeTerminalInputOptions,
  RuntimeTerminalOutputOptions,
  TerminalCapabilityProfile,
  TerminalClock,
  TerminalEnvironment,
  TerminalHost,
  TerminalInput,
  TerminalInputChunk,
  TerminalOutput,
  TerminalOutputChunk,
  TerminalRestoreReason,
  TerminalRestoreResult,
  TerminalSession,
  TerminalSessionOptions,
  TerminalSignal,
  TerminalSignalSource,
  TerminalStateChange,
  TerminalStateSnapshot,
  TerminalViewport
} from './host/index.ts';

export type {
  EndOfInputEvent,
  FocusEvent,
  InputDecodeOptions,
  InputDecoder,
  InputEvent,
  InputPipeline,
  InputPipelineOptions,
  InputPipelineProfile,
  KeyEvent,
  KeyEventLike,
  KeyName,
  KeyboardInputProfileName,
  KeyboardInputProfileRequest,
  MouseAction,
  MouseButton,
  MouseEncoding,
  MouseEvent,
  MouseModifiers,
  PasteEvent,
  ResizeEvent,
  SignalEvent,
  TextInputEvent,
  UnknownInputEvent
} from './input/index.ts';

export type {
  ClipboardWritePolicy,
  ClipboardWriteResult,
  TerminalProtocolWriter,
  TerminalRestorePlan
} from './protocol/index.ts';

export type {
  ExtractTextSelectionInput,
  GraphemeSegment,
  RemovedControlSequence,
  SanitizedTerminalText,
  SanitizeTerminalTextOptions,
  TextCellMetrics,
  TextClipOptions,
  TextClipResult,
  TextEditBuffer,
  TextEditHistory,
  TextEditHistoryGroup,
  TextEditHistoryOperation,
  TextEditHistoryResult,
  TextEditOperation,
  TextHighlightMatch,
  TextHighlightOptions,
  TextLine,
  TextMeasurementOptions,
  TextSelection,
  TerminalTextIndex,
  TextWrapOptions
} from './text/index.ts';

export type {
  BorderGlyphSet,
  BorderGlyphSetDefinition,
  CoreColorToken,
  TerminalDesignTokenDefinition,
  TerminalDesignTokens,
  TerminalSpacingTokens,
  TerminalSymbols,
  TerminalSymbolsDefinition,
  TerminalTheme,
  TerminalThemeDefinition,
  ThemeColor,
  ThemeColorToken,
  ThemeColorTokens
} from './theme/index.ts';
export {
  asciiSymbols,
  catppuccinTheme,
  compactTheme,
  contrastColor,
  createTheme,
  defaultTheme,
  defaultThemes,
  defineTheme,
  deriveSurface,
  draculaTheme,
  ensureContrast,
  gruvboxTheme,
  highContrastTheme,
  mergeDesignTokens,
  mergeThemes,
  minimalTheme,
  modernTheme,
  monochromeTheme,
  noColorTheme,
  nordTheme,
  resolveTerminalStyle,
  resolveThemeColor,
  solarizedTheme,
  themePacks,
  tokyoNightTheme,
  unicodeSymbols
} from './theme/index.ts';

export {
  autocomplete,
  confirm,
  createProgress,
  editor,
  input,
  multiselect,
  password,
  progress,
  runPrompt,
  select
} from './prompts/index.ts';
export type {
  AutocompletePromptOptions,
  ConfirmPromptOptions,
  EditorPromptOptions,
  InputPromptOptions,
  MultiSelectPromptOptions,
  NonTtyMode,
  NonTtyPromptPolicy,
  PasswordPromptOptions,
  ProgressController,
  ProgressOptions,
  ProgressPromptOptions,
  ProgressResult,
  ProgressState,
  PromptAbortReason,
  PromptAbortResult,
  PromptChoice,
  PromptDataSource,
  PromptDataSourceQuery,
  PromptDataSourceResult,
  PromptDefinition,
  PromptEditorAdapter,
  PromptEditorCommand,
  PromptEditorCommandSource,
  PromptEditorRequest,
  PromptEditorResult,
  PromptKind,
  PromptRenderer,
  PromptResult,
  PromptSubmitResult,
  PromptValidationContext,
  PromptValidationResult,
  PromptValidator,
  SelectPromptOptions
} from './prompts/index.ts';

export {
  animationSource,
  createTuiRuntime,
  defineTui,
  intervalSource,
  runTui,
  timeoutSource
} from './tui/index.ts';
export type {
  CursorVisibilityPolicy,
  ProtocolRequirement,
  SessionProtocolOperation,
  SessionProtocolOperationKind,
  SessionProtocolPolicy,
  SessionProtocolSetupResult,
  TuiApp,
  TuiContext,
  TuiDefinition,
  TuiEventSource,
  TuiEventDelivery,
  TuiEffect,
  TuiEffectContext,
  TuiEffectFailure,
  TuiExit,
  TuiExitHandler,
  TuiExitRequest,
  TuiInit,
  TuiInputResult,
  TuiKeyBinding,
  TuiKeyBindingContext,
  TuiKeyBindingPhase,
  TuiMessageSource,
  TuiNonTtyMode,
  TuiNonTtyPolicy,
  TuiRunOptions,
  TuiRuntime,
  TuiRuntimeChange,
  TuiRuntimeOptions,
  TuiSubscriptionContext,
  TuiSourceLifecycle,
  TuiSubscriptions,
  TuiUpdate,
  TuiUpdateResult,
  TuiView
} from './tui/index.ts';

export {
  activityFeed,
  activityIndicator,
  barChart,
  button,
  canvas,
  chart,
  checkbox,
  checkboxList,
  colorPicker,
  commandBar,
  contextMenu,
  datePicker,
  divider,
  dropdown,
  field,
  form,
  gauge,
  heatmap,
  helpBar,
  label,
  list,
  menu,
  menuBar,
  notificationStack,
  numberInput,
  paginator,
  palette,
  progressBar,
  radioGroup,
  rangeSlider,
  richText,
  scrollback,
  selectBox,
  slider,
  sparkline,
  spinner,
  statusBar,
  structuredBlock,
  table,
  text,
  textArea,
  textInput,
  toggleSwitch,
  tooltip,
  tree
} from './components/index.ts';
export type {
  AccessibleNodeDefinition,
  ActivityFeedOptions,
  ActivityIndicatorOptions,
  BarChartItem,
  BarChartOptions,
  ButtonOptions,
  CanvasPainter,
  CanvasPainterInput,
  CanvasOptions,
  ChartInterpolation,
  ChartPointEvent,
  ChartPointSelection,
  ChartSampleAlign,
  ChartSampleMode,
  ChartSeries,
  ChartSeriesKind,
  ChartOptions,
  CheckboxListOptions,
  CheckboxOptions,
  ColorPickerOption,
  ColorPickerOptions,
  CommandBarDisplay,
  CommandBarValidation,
  CommandBarOptions,
  ComponentFocusOptions,
  ComponentKeyBindings,
  ComponentLayerOptions,
  ComponentMeta,
  ComponentOptions,
  ComponentOverflowPriority,
  ComponentStyleSlots,
  ComponentTextInputHandlers,
  DividerLineKind,
  DividerOrientation,
  DividerOptions,
  DropdownOptions,
  Element,
  ElementChildren,
  FieldOptions,
  FormOptions,
  GaugeVariant,
  GaugeOptions,
  HeatmapCell,
  HeatmapSelection,
  HeatmapOptions,
  HelpBarOptions,
  LabelOptions,
  ListOptions,
  MenuBarOptions,
  MenuItem,
  MenuOptions,
  NotificationItem,
  NotificationPlacement,
  NotificationStackOptions,
  NotificationTone,
  NumberInputOptions,
  PaletteOptions,
  PaginatorOptions,
  ProgressBarDisplay,
  ProgressBarLabelPosition,
  ProgressBarOptions,
  RadioGroupOptions,
  RangeSliderValue,
  RangeSliderOptions,
  RichTextOptions,
  ScrollbackItem,
  ScrollbackOptions,
  SelectBoxOptions,
  SliderOptions,
  SparklineOptions,
  SpinnerOptions,
  StatusBarOptions,
  StructuredBlock,
  StructuredBlockOptions,
  TabItem,
  TableCellPointerSelection,
  TableCellRenderInput,
  TableCellSelection,
  TableColumn,
  TableColumnAlignment,
  TableColumnSemantic,
  TableColumnWidth,
  TableDensity,
  TablePointerSelection,
  TableSortDirection,
  TableOptions,
  TextAreaHighlight,
  TextAreaLineNumberOptions,
  TextAreaOptions,
  TextAreaWrapOptions,
  TextInputOptions,
  TextOptions,
  ToggleSwitchOptions,
  TooltipPlacement,
  TooltipTone,
  TooltipOptions,
  TreeDisclosureAction,
  TreeNode,
  TreeOptions,
  ValueScale,
  ValueScaleStop,
  ActionItem,
  ComponentActionTone,
  ChoiceItem,
  FieldItem,
  ComponentFocusScope,
  HierarchyItem,
  ItemBase,
  HelpBinding,
  LogLevel,
  NavigationItem,
  ProcessStatus,
  RecordStatus,
  SearchEntry,
  ComponentStatus,
  SuggestionItem,
  TextRole,
  TitledItem,
  ComponentTone,
  TreeItemBase,
  ComponentValidationTone,
  ComponentVisualState
} from './components/index.ts';

export {
  absolute,
  defineBreakpoints,
  grid,
  modal,
  overlay,
  responsive,
  row,
  splitPane,
  stack,
  surface,
  tabs,
  viewport,
  viewportVariant
} from './layout/index.ts';
export type {
  AbsoluteOptions,
  GridAreasOptions,
  GridLayoutOptions,
  GridOptions,
  LayoutAlignment,
  LayoutFlowOptions,
  LayoutInsetInput,
  LayoutInsets,
  LayoutJustification,
  LayoutOverflow,
  LayoutSize,
  ModalOptions,
  OverlayOptions,
  ResponsiveBreakpointMap,
  ResponsiveVariants,
  RowOptions,
  SplitPaneOptions,
  StackOptions,
  SurfaceOptions,
  TabsOptions,
  ViewportDimensions,
  ViewportOptions
} from './layout/index.ts';

export {
  accessibleRoles,
  accessibleSources,
  findAccessibleNode,
  toAccessibleSnapshot,
  validateAccessibleSnapshot
} from './accessibility/index.ts';
export type {
  AccessibilityOptions,
  AccessibleLiveRegion,
  AccessibleNode,
  AccessiblePosition,
  AccessibleProgress,
  AccessibleRole,
  AccessibleScope,
  AccessibleScopeKind,
  AccessibleSnapshot,
  AccessibleSnapshotInput,
  AccessibleSnapshotSource,
  AccessibleValue,
  AccessibleWindow
} from './accessibility/index.ts';

export { redactTranscript, replayTranscript, validateTranscript } from './transcript/index.ts';
export type {
  InteractionResult,
  InteractionTranscript,
  InteractionTranscriptStep,
  RedactionPolicy,
  TranscriptPolicy,
  TranscriptRecorder,
  TranscriptRecorderOptions,
  TranscriptRedaction,
  TranscriptReplayTarget,
  TranscriptSource
} from './transcript/index.ts';

export {
  assertFocus,
  assertHitTarget,
  assertNoSecretLeak,
  assertSelected,
  assertTerminalRestored,
  assertVisibleText,
  createPtyTerminalHarness,
  createTerminalHarness,
  createVisualSnapshot,
  isPtyHarnessUnavailable,
  runInteractionScript
} from './testing/index.ts';
export type {
  FocusAssertion,
  HitTargetAssertion,
  InteractionScript,
  InteractionStep,
  PtyTerminalHarness,
  PtyTerminalHarnessOptions,
  PtyTerminalHarnessResult,
  SelectedAssertion,
  SnapshotAssertion,
  TerminalHarness,
  TerminalHarnessOptions,
  VisibleTextAssertion,
  VisualSnapshotArtifacts,
  VisualSnapshotInput
} from './testing/index.ts';

export * as host from './host/index.ts';
export * as protocol from './protocol/index.ts';
export * as theme from './theme/index.ts';
export * as prompts from './prompts/index.ts';
export * as tui from './tui/index.ts';
export * as components from './components/index.ts';
export * as layout from './layout/index.ts';
export * as behavior from './behavior/index.ts';
export * as renderer from './renderer/index.ts';
export * as accessibility from './accessibility/index.ts';
export * as transcript from './transcript/index.ts';
export * as testing from './testing/index.ts';
export * as schemas from './schemas/index.ts';
