export { terminalUiPackage } from './package.ts';
export type { RuntimeTarget, TerminalUiEntrypoint, TerminalUiPackage } from './package.ts';
export type { Result } from './result.ts';
export { ok, err } from './result.ts';
export type {
  TerminalDiagnostic,
  TerminalDiagnosticCode,
  TerminalDiagnosticValue,
  TerminalSeverity
} from './diagnostics.ts';
export { diagnostic, terminalDiagnosticCodes } from './diagnostics.ts';
export { TerminalUiError } from './errors.ts';

export {
  createBunTerminalHost,
  createDenoTerminalHost,
  createMemoryTerminalHost,
  createNodeTerminalHost,
  createPtyTerminalHost,
  createTerminalHost,
  detectTerminalCapabilities,
  restoreTerminalState
} from './host/index.ts';
export type {
  BunTerminalHostOptions,
  CreateTerminalHostOptions,
  DenoTerminalHostOptions,
  MemoryTerminalHost,
  MemoryTerminalHostOptions,
  NodeProcessLike,
  NodeReadableTerminalStream,
  NodeTerminalHostOptions,
  NodeTerminalSignal,
  NodeWritableTerminalStream,
  PtyTerminalHost,
  PtyTerminalHostOptions,
  RuntimeInputSource,
  RuntimeTerminalInputOptions,
  RuntimeTerminalOutputOptions,
  TerminalCapabilities,
  TerminalClock,
  TerminalEnvironment,
  TerminalHost,
  TerminalInput,
  TerminalInputChunk,
  TerminalOutput,
  TerminalOutputChunk,
  TerminalRestoreReason,
  TerminalRestoreResult,
  TerminalSession,
  TerminalSessionOptions,
  TerminalSignal,
  TerminalSignalSource,
  TerminalStateChange,
  TerminalStateSnapshot,
  TerminalViewport
} from './host/index.ts';
export type {
  EndOfInputEvent,
  FocusEvent,
  InputDecodeOptions,
  InputDecoder,
  InputEvent,
  KeyEvent,
  KeyEventLike,
  KeyName,
  MouseAction,
  MouseButton,
  MouseEncoding,
  MouseEvent,
  MouseModifiers,
  PasteEvent,
  ResizeEvent,
  SignalEvent,
  TextInputEvent,
  UnknownInputEvent
} from './input/index.ts';
export type {
  ClipboardWritePolicy,
  ClipboardWriteResult,
  TerminalProtocolWriter,
  TerminalRestorePlan
} from './protocol/index.ts';
export type {
  ExtractTextSelectionInput,
  GraphemeSegment,
  RemovedControlSequence,
  SanitizedTerminalText,
  SanitizeTerminalTextOptions,
  TextCellMetrics,
  TextAreaEditBuffer,
  TextAreaEditOperation,
  TextClipOptions,
  TextClipResult,
  TextEditBuffer,
  TextEditOperation,
  TextLine,
  TextMeasurementOptions,
  TextSelection,
  TerminalTextIndex,
  TextWrapOptions
} from './text/index.ts';
export type {
  BorderGlyphSet,
  BorderGlyphSetDefinition,
  CoreThemeToken,
  TerminalSpacing,
  TerminalSymbols,
  TerminalSymbolsDefinition,
  TerminalTheme,
  TerminalThemeDefinition,
  ThemeColor,
  ThemeToken
} from './theme/index.ts';
export {
  asciiSymbols,
  compactTheme,
  catppuccinTheme,
  contrastColor,
  defaultTheme,
  defaultThemes,
  deriveSurface,
  draculaTheme,
  ensureContrast,
  defineTheme,
  gruvboxTheme,
  highContrastTheme,
  mergeThemes,
  minimalTheme,
  modernTheme,
  monochromeTheme,
  nordTheme,
  noColorTheme,
  resolveTerminalStyle,
  resolveThemeColor,
  solarizedTheme,
  themePacks,
  tokyoNightTheme,
  unicodeSymbols
} from './theme/index.ts';

export {
  autocomplete,
  confirm,
  createProgress,
  editor,
  input,
  multiselect,
  password,
  progress,
  runPrompt,
  select
} from './prompts/index.ts';
export type {
  AutocompletePromptOptions,
  ConfirmPromptOptions,
  EditorPromptOptions,
  InputPromptOptions,
  MultiSelectPromptOptions,
  NonTtyMode,
  NonTtyPromptPolicy,
  PasswordPromptOptions,
  ProgressController,
  PromptEditorAdapter,
  PromptEditorCommand,
  PromptEditorCommandSource,
  PromptEditorRequest,
  PromptEditorResult,
  ProgressOptions,
  ProgressPromptOptions,
  ProgressResult,
  ProgressState,
  PromptAbortReason,
  PromptAbortResult,
  PromptChoice,
  PromptDataSource,
  PromptDataSourceQuery,
  PromptDataSourceResult,
  PromptDefinition,
  PromptKind,
  PromptProgressState,
  PromptRenderer,
  PromptResult,
  PromptSubmitResult,
  PromptValidationContext,
  PromptValidationResult,
  PromptValidator,
  SelectPromptOptions
} from './prompts/index.ts';
export { createShell, runShell } from './shell/index.ts';
export { createCliCoreCommandSource, createCommandPalette } from './shell/index.ts';
export type {
  CliCoreCommandSourceInput,
  CliCoreShellAdapter,
  CommandPalette,
  CommandPaletteOptions,
  ShellCheckpoint,
  ShellCheckpointPolicy,
  ShellArgvParser,
  ShellCommandParseInput,
  ShellCommandSource,
  ShellEvent,
  ShellExit,
  ShellHelpPreview,
  ShellHistoryEntry,
  ShellHistoryProvider,
  ShellMode,
  ShellNonTtyPolicy,
  ShellOptions,
  ShellPaletteAction,
  ShellPromptRenderer,
  ShellRunPolicy,
  ShellRunRequest,
  ShellState,
  ShellSuggestion,
  ShellTranscript,
  ShellTranscriptCommand,
  ShellTranscriptCommandStatus,
  ShellTransientLayer,
  TerminalShell
} from './shell/index.ts';
export {
  activeScreen,
  clipRenderSpans,
  commandBarReducer,
  compositeRegions,
  createCanvas2D,
  createFrameBuffer,
  createDirtyRegionSet,
  createTuiRuntime,
  dataWindow,
  dirtyRegionsForRegionChanges,
  createScrollState,
  defineTui,
  diffFrames,
  drawBorder,
  extractScrollbackSelectionText,
  filterPaletteEntries,
  gridCellRects,
  layoutWidget,
  normalizeScrollState,
  paletteWindow,
  paginationWindow,
  renderDiffAnsi,
  renderFrameAnsi,
  renderFrameDebug,
  renderFramePlain,
  renderWidgetFrame,
  renderWidgetRegions,
  renderScrollbars,
  boxDrawingJoinPass,
  blockGlyph,
  blockSpan,
  brailleCellForPoint,
  brailleCharacter,
  brailleMaskForSubcell,
  horizontalAxis,
  integerPoint,
  linePoints,
  rectInteriorPoints,
  rectStrokePoints,
  tooltipLines,
  verticalAxis,
  animationSource,
  intervalSource,
  sameFrameCell,
  sameFrameCellSource,
  serializeRenderSpansStateful,
  sameTerminalColor,
  sameTerminalLink,
  sameTerminalStyle,
  screenStackReducer,
  rowWindow,
  scrollReducer,
  scrollStateFromUnknown,
  scrollbarLayout,
  scrollbackWindow,
  nextSpinnerFrameIndex,
  normalizeSpinnerFrameIndex,
  spinnerReducer,
  splitTracks,
  treeReducer,
  visibleWindowFromScroll,
  timeoutSource,
  runTui
} from './tui/index.ts';
export type {
  CommandBarAction,
  CommandBarState,
  DataWindow,
  DataWindowInput,
  DiffFramesOptions,
  DirtyRegionSet,
  PaletteFilterResult,
  PaletteWindowInput,
  BorderStyle,
  AxisLine,
  BlockGlyph,
  BrailleCellPoint,
  Canvas2D,
  CanvasPoint,
  AnsiStyleState,
  CreateScrollStateInput,
  FocusTarget,
  Frame,
  FrameBuffer,
  FrameCell,
  FrameCellSource,
  FrameHitTarget,
  FramePass,
  FramePassContext,
  FrameSemanticRole,
  FrameRowDiff,
  HitTarget,
  PaginationInput,
  PaginationWindow,
  GridLayoutOptions,
  Layer,
  LayoutAlignment,
  LayoutFlowOptions,
  LayoutInsetInput,
  LayoutInsets,
  LayoutJustification,
  LayoutOverflow,
  LayoutSize,
  LayoutNode,
  Rect,
  RenderBlock,
  RenderDiff,
  RenderRegion,
  RenderWidgetFrameProjection,
  RenderLine,
  RenderOperation,
  RenderSerializeOptions,
  RenderSpan,
  StrokeFillOptions,
  Screen,
  ScreenStack,
  ScreenStackAction,
  ScrollAction,
  ScrollState,
  ScrollbarLayout,
  ScrollbarOptions,
  ScrollbarState,
  ScrollbarThumb,
  ScrollbarTrack,
  SpinnerAction,
  SpinnerReducerOptions,
  SpinnerState,
  ExtractScrollbackSelectionTextInput,
  ScrollbackTextSegment,
  ScrollbackVisibleRow,
  ScrollbackWindow,
  ScrollVisibleWindow,
  TerminalColor,
  TerminalLink,
  TerminalStyle,
  TooltipLine,
  TuiApp,
  TuiCommand,
  TuiContext,
  TuiDefinition,
  TuiEventSource,
  TuiExit,
  TuiExitHandler,
  TuiExitRequest,
  TuiInit,
  TuiInputResult,
  TuiMessageSource,
  TuiNonTtyMode,
  TuiNonTtyPolicy,
  TuiRuntime,
  TuiRuntimeChange,
  TuiRuntimeOptions,
  TuiSubscriptionContext,
  TuiSubscriptions,
  TuiUpdate,
  TuiUpdateResult,
  TuiView,
  TreeAction,
  WidgetAccessibilityInput,
  WidgetFocusInput,
  WidgetHitInput,
  WidgetLayoutInput,
  WidgetMeasureInput,
  WidgetMeasureResult,
  WidgetRenderer,
  WidgetRenderInput
} from './tui/index.ts';
export type {
  AccessibleNodeDefinition,
  ActivityIndicatorStatus,
  ActivityIndicatorWidgetOptions,
  AbsoluteWidgetOptions,
  BarChartItem,
  BarChartWidgetOptions,
  BoxWidgetOptions,
  ButtonWidgetOptions,
  CanvasPainter,
  CanvasPainterInput,
  CanvasWidgetOptions,
  ChartSeries,
  ChartWidgetOptions,
  CheckboxWidgetOptions,
  CommandBarSuggestion,
  CommandBarValidation,
  CommandBarValidationTone,
  CommandBarWidgetOptions,
  CommandPaletteEntry,
  CommandPaletteWidgetOptions,
  CustomWidgetOptions,
  CustomWidgetRuntime,
  FieldWidgetOptions,
  FormOption,
  FormWidgetOptions,
  GridWidgetOptions,
  HelpBarWidgetOptions,
  HelpBinding,
  InputFieldWidgetOptions,
  LabelWidgetOptions,
  ListWidgetOptions,
  ContextMenuWidgetOptions,
  DropdownWidgetOptions,
  MenuBarWidgetOptions,
  MenuItem,
  MenuWidgetOptions,
  ModalWidgetOptions,
  NumberInputWidgetOptions,
  OverlayWidgetOptions,
  PaletteEntry,
  PaletteWidgetOptions,
  PaginatorWidgetOptions,
  ProgressBarLabelPosition,
  ProgressBarMode,
  ProgressBarWidgetOptions,
  RadioGroupWidgetOptions,
  RichTextWidgetOptions,
  RowWidgetOptions,
  ScrollbackItem,
  ScrollbackWidgetOptions,
  SelectBoxWidgetOptions,
  SparklineWidgetOptions,
  SpinnerWidgetOptions,
  StackWidgetOptions,
  StructuredBlock,
  StructuredBlockField,
  StructuredBlockStatus,
  StructuredBlockWidgetOptions,
  StatusBarWidgetOptions,
  SurfaceWidgetOptions,
  SplitPaneWidgetOptions,
  TabItem,
  TableCellSelection,
  TableCellRenderInput,
  TableColumnAlignment,
  TableColumn,
  TableColumnWidth,
  TableSortDirection,
  TableWidgetOptions,
  TabsWidgetOptions,
  TextAreaWidgetOptions,
  TextInputWidgetOptions,
  TextWidgetOptions,
  TreeNode,
  TreeWidgetOptions,
  ViewportWidgetOptions,
  ActivityFeedWidgetOptions,
  Widget,
  WidgetChildren,
  WidgetFocusOptions,
  WidgetFocusScope,
  WidgetInputMap,
  WidgetKeyMap,
  WidgetKind,
  WidgetLayerOptions,
  WidgetProps,
  WidgetStyleSlots,
  WidgetVisualState
} from './widgets/index.ts';
export {
  accessibleRoles,
  accessibleSources,
  findAccessibleNode,
  toAccessibleSnapshot,
  validateAccessibleSnapshot
} from './accessibility/index.ts';
export type {
  AccessibilityOptions,
  AccessibleNode,
  AccessibleProgress,
  AccessibleRole,
  AccessibleSnapshot,
  AccessibleSnapshotInput,
  AccessibleSnapshotSource,
  AccessibleValue
} from './accessibility/index.ts';
export { redactTranscript, replayTranscript, validateTranscript } from './transcript/index.ts';
export type {
  InteractionResult,
  InteractionTranscript,
  InteractionTranscriptStep,
  RedactionPolicy,
  TranscriptPolicy,
  TranscriptRecorderOptions,
  TranscriptRecorder,
  TranscriptRedaction,
  TranscriptReplayTarget,
  TranscriptSource
} from './transcript/index.ts';
export {
  assertFocus,
  assertHitTarget,
  assertNoSecretLeak,
  assertSelected,
  assertTerminalRestored,
  assertVisibleText,
  createPtyTerminalHarness,
  createTerminalHarness,
  createVisualSnapshot,
  isPtyHarnessUnavailable,
  runInteractionScript
} from './testing/index.ts';
export type {
  FocusAssertion,
  HitTargetAssertion,
  InteractionScript,
  InteractionStep,
  PtyTerminalHarness,
  PtyTerminalHarnessOptions,
  PtyTerminalHarnessResult,
  SelectedAssertion,
  SnapshotAssertion,
  TerminalHarness,
  TerminalHarnessOptions,
  VisibleTextAssertion,
  VisualSnapshotArtifacts,
  VisualSnapshotInput
} from './testing/index.ts';

export * as host from './host/index.ts';
export * as protocol from './protocol/index.ts';
export * as text from './text/index.ts';
export * as theme from './theme/index.ts';
export * as prompts from './prompts/index.ts';
export * as shell from './shell/index.ts';
export * as tui from './tui/index.ts';
export * as widgets from './widgets/index.ts';
export * as accessibility from './accessibility/index.ts';
export * as transcript from './transcript/index.ts';
export * as testing from './testing/index.ts';
export * as schemas from './schemas/index.ts';
